### ISSUE TITLE
Works fine from IntelliJ IDEA. But fails to execute from terminal

### ISSUE THREAD

**Issue by ghoshbishakh** [ItsForkIT/psync-pc#1]
@archie94 can you look into it?

**Comment by archie94** [comment]
@ghoshbishakh I am downloading the IDE. What is the error you are getting?

**Comment by archie94** [comment]
@ghoshbishakh can we create a jar file and run from terminal?

**Comment by ghoshbishakh** [comment]
@archie94 I am not familiar with java, try whatever you feel right.

**Comment by archie94** [comment]
@ghoshbishakh created jar and works in terminal.

**Comment by ghoshbishakh** [comment]
@archie94 great. can you somehow test it once?

**Comment by archie94** [comment]
@ghoshbishakh I tested the jar file with an android device. Found these bugs:
1. The pc app is unable to find the list of missing files from the android device.
2. java.io.FileNotFoundException: /www/database/fileDB.txt (Permission denied) when thread tries to find the list of its files.
3. The service is not stopping on closing the app from terminal.
