### ISSUE TITLE
Maintain a crash log. 

### ISSUE THREAD

**Issue by archie94** [ItsForkIT/psync-pc#12]
When the application crashes can we keep the crash log in a file for further inspection? It will remove the hassle of reconnecting to a terminal and replicating the bug.

**Comment by archie94** [comment]
Check [this](http://stackoverflow.com/questions/21089278/how-do-i-make-my-jar-application-generate-a-crash-log-file) out! If it works it is ideal for us.

**Comment by ghoshbishakh** [comment]
@archie94 ato sokale ki korcho

**Comment by archie94** [comment]
@ghoshbishakh practice!! roj roj 3 te kore ghumote gele office miss korbo sure! XD

**Comment by archie94** [comment]
Closed via ebfddd26b5fe2cdbd4cb39b97eb116a739d433a4
